// SET MIMETYPE FOR SELECT COMPONENT

export const programmingLanguages = [
    { label: 'C', value: 'text/x-csrc' },
    { label: 'C++', value: 'text/x-c++src' },
    { label: 'Java', value: 'text/x-java' },
    { label: 'C#', value: 'text/x-csharp' },
    { label: 'Objective C', value: 'text/x-objectivec' },
    { label: 'Scala', value: 'text/x-scala' },
    { label: 'Css', value: 'text/css' },
    { label: 'Scss', value: 'text/x-scss' },
    { label: 'Less', value: 'text/x-less' },
    { label: 'DockerFile', value: 'text/x-dockerfile' },
    { label: 'ErLang', value: 'text/x-erlang' },
    { label: 'Go', value: 'text/x-go' },
    { label: 'JavaScript', value: 'text/javascript' },
    { label: 'HTML', value: 'text/html' },
    { label: 'React/JSX', value: 'text/jsx' },
    { label: 'JSON', value: 'application/json' },
    { label: 'TypeScript', value: 'text/typescript' },
    { label: 'Julia', value: 'text/x-julia' },
    { label: 'Lua', value: 'text/x-lua' },
    { label: 'Php', value: 'application/x-httpd-php' },
    { label: 'Powershell', value: 'application/x-powershell' },
    { label: 'Python', value: 'text/x-python' },
    { label: 'Ruby', value: 'text/x-ruby' },
    { label: 'Sass', value: 'text/x-sass' },
    { label: 'Shell', value: 'text/x-sh' },
    { label: 'SQL(Postgres)', value: 'text/x-pgsql' },
    { label: 'SQL(MySql)', value: 'text/x-mysql' },
    { label: 'Swift', value: 'text/x-swift' },
    { label: 'Vue', value: 'text/x-vue' },
];
